"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from loguru import logger
from decouple import config
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
logger.add(
    BASE_DIR / "logs" / "log_{time:YYYY-MM-DD}.log", rotation="1 week", level="DEBUG"
)
# 增加 apps 路径
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]

CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1", "http://localhost",]
DOMAIN = config('DOMAIN')
if DOMAIN:
    ALLOWED_HOSTS.append(DOMAIN)
    CSRF_TRUSTED_ORIGINS += [
        f'https://{DOMAIN}',
    ]

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'rest_framework',
    # 'rest_framework_simplejwt',
    'account',
    'item',
    'trade',
    'front',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'core.middleware.CustomMiddleware' # 如果大规模使用Json响应，推荐开启格式化中间件
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# mysql配置
DATABASES = {
    'default': {
        'ENGINE': config('ENGINE', 'django.db.backends.mysql'),
        'NAME': config('MYSQL_DATABASE'),
        'USER': config('DB_USER', 'root'),
        'PASSWORD': config('MYSQL_ROOT_PASSWORD'),
        'HOST': config('DB_HOST', 'localhost'),
        'PORT': config('DB_PORT', '3306'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 语言与时间
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/' # 访问静态文件URL
STATICFILES_DIRS = [BASE_DIR / "static"] # 开发时查找静态文件的目录列表
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'  # 访问媒体文件的URL
MEDIA_ROOT = BASE_DIR / 'media'  # 存储上传文件的位置

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/auth/login'
AUTH_USER_MODEL = 'account.CustomUser' # 自定义用户

# ### drf 配置 ###
# REST_FRAMEWORK = {
#     # 全局认证类
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication', # 移动端/SPA
#         'rest_framework.authentication.SessionAuthentication', # 浏览器/Django admin
#     ),
#     # 全局权限类
#     # 'DEFAULT_PERMISSION_CLASSES': (
#     #     'core.permissions.IsAdminOrReadOnly',
#     # ),
#     # 全局分页类
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10,
#     # 全局错误类
#     'EXCEPTION_HANDLER': 'core.exception.CustomExceptionHandler',

#     # 限流类
#     # 'DEFAULT_THROTTLE_CLASSES': [
#     #     'rest_framework.throttling.AnonRateThrottle', # 针对匿名用户
#     #     'rest_framework.throttling.UserRateThrottle', # 针对登录用户
#     # ],
#     # 限流规则 （规则对应上面的类，缺一少一不可，根据网站规则决定限流量）
#     # 'DEFAULT_THROTTLE_RATES': {
#     #     'anon': '50/minute',
#     #     'user': '100/day',
#     #     # 'login': '10/minute',
#     #     # 'register': '5/minute',
#     # },
# }

# from datetime import timedelta
# SIMPLE_JWT = {
#     "TOKEN_OBTAIN_SERIALIZER": "core.serializer.CustomTokenObtainPairSerializer",

#     # 1. 令牌生命周期（最常修改）
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # 访问令牌有效时间
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # 刷新令牌有效时间

#     # 2. 安全相关（根据需求选择）
#     "ROTATE_REFRESH_TOKENS": False,  # 刷新时是否生成新refresh_token
#     "BLACKLIST_AFTER_ROTATION": False,  # 刷新后是否将旧令牌加入黑名单

#     # 3. 算法和密钥
#     "ALGORITHM": "HS256",  # 加密算法（HS256/HS384/HS512/RS256等）
#     "SIGNING_KEY": SECRET_KEY, # 密钥

#     # 4. 认证头配置
#     "AUTH_HEADER_TYPES": ("JWT",),  # 认证头类型
#     "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",  # 请求头名称
#     "UPDATE_LAST_LOGIN": False,  # 是否更新最后登录时间
#     "USER_ID_FIELD": "id",  # 用户模型ID字段
#     "USER_ID_CLAIM": "user_id",  # JWT中用户ID的声明字段
#     "CHECK_USER_IS_ACTIVE": True,  # 检查用户是否激活
# }

# 后台首页
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'

# 自定义左侧图标
SIMPLEUI_ICON = {
    '项目管理': 'fa-chisel fa-regular fa-list',
    '项目': 'fa-chisel fa-regular fa-star'
}




SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")